name: retallm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.7.2
  - bzip2=1.0.8
  - cairo=1.16.0
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - graphite2=1.3.13
  - harfbuzz=5.3.0
  - icu=70.1
  - jpeg=9e
  - keyutils=1.6.1
  - lcms2=2.14
  - lerc=4.0.0
  - libcups=2.3.3
  - libdeflate=1.13
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - libnsl=2.0.0
  - libpng=1.6.38
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.13
  - openjdk=11.0.15
  - pcre2=10.40
  - pixman=0.40.0
  - pthread-stubs=0.4
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - zlib=1.2.13
  - zstd=1.5.2
  - ca-certificates=2023.01.10
  - krb5=1.19.4
  - ld_impl_linux-64=2.38
  - libedit=3.1.20221030
  - ncurses=6.3
  - openssl=1.1.1t
  - pip=23.0.1
  - pypdf2=2.10.5
  - python=3.8.16
  - readline=8.1.2
  - setuptools=66.0.0
  - sqlite=3.40.1
  - tk=8.6.12
  - typing_extensions=4.5.0
  - wheel=0.38.4
  - xz=5.2.10
  - pip:
    - accelerate==0.18.0
    - aiofiles==23.1.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - altair==4.2.2
    - anyio==3.6.2
    - async-timeout==4.0.2
    - attrs==23.1.0
    - backports.zoneinfo==0.2.1
    - beautifulsoup4==4.12.2
    - blinker==1.6.2
    - blis==0.7.9
    - bs4==0.0.1
    - cachetools==5.3.0
    - catalogue==2.0.8
    - certifi==2022.12.7
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cmake==3.26.3
    - coloredlogs==15.0.1
    - confection==0.0.4
    - contourpy==1.0.7
    - cpm-kernels==1.0.11
    - cycler==0.11.0
    - cymem==2.0.7
    - cython==0.29.34
    - decorator==5.1.1
    - entrypoints==0.4
    - faiss-cpu==1.7.4
    - faiss-gpu==1.7.2
    - fastapi==0.95.1
    - ffmpy==0.3.0
    - filelock==3.12.0
    - flatbuffers==23.3.3
    - fonttools==4.39.3
    - frozenlist==1.3.3
    - fsspec==2023.4.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - gradio==3.28.1
    - gradio_client==0.1.4
    - h11==0.14.0
    - httpcore==0.17.0
    - httpx==0.24.0
    - huggingface-hub==0.14.1
    - humanfriendly==10.0
    - idna==3.4
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonlines==3.1.0
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - latex2mathml==3.75.3
    - lightgbm==3.3.5
    - linkify-it-py==2.0.0
    - lit==16.0.2
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mdit-py-plugins==0.3.3
    - mdtex2html==1.2.0
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - murmurhash==1.0.9
    - networkx==3.1
    - nmslib==2.1.1
    - numpy==1.24.3
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - onnxruntime==1.14.1
    - orjson==3.8.11
    - packaging==23.1
    - pandas==2.0.1
    - pathy==0.10.1
    - pillow==9.5.0
    - pkgutil_resolve_name==1.3.10
    - preshed==3.0.8
    - protobuf==3.20.3
    - psutil==5.9.5
    - pyarrow==11.0.0
    - pybind11==2.6.1
    - pydantic==1.10.7
    - pydeck==0.8.1b0
    - pydub==0.25.1
    - pygments==2.15.1
    - pyjnius==1.4.2
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pyserini==0.21.0
    - pysolr==3.9.0
    - python-dateutil==2.8.2
    - python-multipart==0.0.6
    - pytrec-eval==0.5
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - regex==2023.3.23
    - requests==2.29.0
    - rich==13.3.5
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - semantic-version==2.10.0
    - sentencepiece==0.1.98
    - six==1.16.0
    - smart-open==6.3.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - spacy==3.5.2
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.4.6
    - starlette==0.26.1
    - streamlit==1.22.0
    - streamlit-chat==0.0.2.2
    - sympy==1.11.1
    - tenacity==8.2.2
    - thinc==8.1.9
    - threadpoolctl==3.1.0
    - tokenizers==0.13.3
    - toml==0.10.2
    - toolz==0.12.0
    - torch==2.0.0
    - tornado==6.3.1
    - tqdm==4.65.0
    - transformers==4.28.0
    - triton==2.0.0
    - typer==0.7.0
    - tzdata==2023.3
    - tzlocal==4.3
    - uc-micro-py==1.0.1
    - ujson==5.7.0
    - urllib3==1.26.15
    - uvicorn==0.22.0
    - validators==0.20.0
    - wasabi==1.1.1
    - watchdog==3.0.0
    - websockets==11.0.2
    - yarl==1.9.2
    - zipp==3.15.0
    - openai==0.27.6